CC = gcc
AR = ar

TARGET_DIR  = ./
TARGET_LIB = lua

SRCS    = $(wildcard source/*.c)
CFLAGS  = -fno-common -fno-exceptions

#===============================================================#

CXFLAGS		= -Wall -O3 -DNDEBUG
TARGET_NAME = lib$(TARGET_LIB).a
OBJDIR      = build


OBJS		= $(patsubst %, $(OBJDIR)/%.o, $(basename $(SRCS)))
DST_OBJS	= $(patsubst %, $(OBJDIR)/%.o, $(basename $(notdir $(SRCS))))

CXXFLAGS	= $(INCDIRS) -I./source $(CXFLAGS) $(CFLAGS)

TARGET      = $(TARGET_DIR)$(TARGET_NAME)

all: $(TARGET)

$(TARGET): $(TARGET_DIR) $(OBJDIR) $(OBJS)
	$(AR) -r $(TARGET) $(DST_OBJS)

$(OBJS): $(OBJDIR)/%.o: %.c
	$(CC) $(CXXFLAGS) -c $< -o $(OBJDIR)/$(notdir $@)

$(OBJDIR):
	mkdir -p $@

$(TARGET_DIR):
	mkdir -p $@

clean:
	rm -rf $(TARGET) $(OBJDIR) $(OBJS)
